feat : react-router 추가,introduce.js 추가
GDSC-Daejin/react-task pull request #5
Opened 2021-11-22 14:26 UTC by dongddddd

- react-router 추가
- introduce page 추가

2021-11-22 14:30 UTC, HyeokE requested changes

2021-11-22 14:30 UTC, HyeokE commented on src/pages/Introduce.js
> +            <br>
`<br/>` 로 변경해주세요

2021-11-22 14:30 UTC, HyeokE commented on src/pages/Pages.js
> +    <Route path="/introduce" component={Introduce.js} />
`<Route path="/introduce" component={Introduce} />` 로 변경해주세요

2021-11-22 14:30 UTC, HyeokE commented on src/pages/Introduce.js
> +            <br>
`<br/>` 태그를 넣으신 이유가 있나요?

2021-11-22 14:36 UTC, dongddddd commented on src/pages/Introduce.js
> +            <br>
<TopMargin/>태그를 보고 공백태그여서 혹시 줄바꿈하면 될까 해서 <br/>태그를썼습니다.

2021-11-22 14:36 UTC, dongddddd commented on src/pages/Pages.js
> +    <Route path="/introduce" component={Introduce.js} />
넵

2021-11-23 03:28 UTC, dongddddd commented
<img width="573" alt="스크린샷 2021-11-23 오후 12 26 11" src="https://user-images.githubusercontent.com/86543136/142967182-71490e86-6bc1-43ae-ba18-abf112a40fa4.png">

2021-11-23 04:15 UTC, HyeokE commented
> <img alt="스크린샷 2021-11-23 오후 12 26 11" width="573" src="https://user-images.githubusercontent.com/86543136/142967182-71490e86-6bc1-43ae-ba18-abf112a40fa4.png">

`App.js`에 import 잘 되어있는지 확인해주시고 Route 세팅해주세요.
+ 제가 route 세팅 해놨습니다. master branch에서 pull하시고 본인 브랜치에 merge해주세요

2021-11-23 04:18 UTC, merged